version: '3'

services:
  phppgadmin:
    image: dockage/phppgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PHP_PG_ADMIN_SERVER_HOST: "145.223.23.191"
      PHP_PG_ADMIN_SERVER_PORT: "5432"
      PHP_PG_ADMIN_SERVER_DESC: "Remote Saamy Agency DB"
      PHP_PG_ADMIN_SERVER_DEFAULTDB: "saamy_agency"
      PHP_PG_ADMIN_DEFAULT_LANG: "english"
